apiVersion: apps/v1
kind: Deployment
metadata:
  name: local-ai-mes-service
spec:
  template:
    spec:
      containers:
        - name: local-ai-mes-service
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
            limits:
              cpu: "2"
              memory: "4Gi"
