apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deployment-package-factory-default
  namespace: deployment-package-factory
  labels:
    app.kubernetes.io/name: deployment-package-factory
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: deployment-package-factory
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: 80
        - protocol: TCP
          port: 8080
        - protocol: TCP
          port: 8096
        - protocol: TCP
          port: 5432
  egress:
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: deployment-package-factory
      ports:
        - protocol: TCP
          port: 5432
        - protocol: TCP
          port: 8096
        - protocol: TCP
          port: 8080
        - protocol: TCP
          port: 80
    - to:
        - ipBlock:
            cidr: 10.96.0.0/12
      ports:
        - protocol: TCP
          port: 443
        - protocol: TCP
          port: 6443
    - to:
        - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: 53
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 443
        - protocol: TCP
          port: 5432
        - protocol: TCP
          port: 80
