apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: deployment-package-factory-data
  namespace: deployment-package-factory
  labels:
    app.kubernetes.io/name: deployment-package-factory
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: __REPLACE_WITH_RWX_STORAGE_CLASS__
  resources:
    requests:
      storage: 100Gi
