apiVersion: v1
kind: ServiceAccount
metadata:
  name: deployment-package-factory
  namespace: deployment-package-factory
  labels:
    app.kubernetes.io/name: deployment-package-factory
automountServiceAccountToken: true
