from __future__ import annotations


def render_install_ps1(installer_version: str, default_mode: str = "k8s") -> str:
    return (
        "param(\n"
        "  [ValidateSet('k8s', 'docker-compose')]\n"
        f"  [string]$Mode = '{default_mode}',\n"
        "  [switch]$SkipVerify,\n"
        "  [switch]$SkipDryRun,\n"
        "  [switch]$SkipHealthCheck,\n"
        "  [switch]$SkipDiagnostics,\n"
        "  [switch]$Yes\n"
        ")\n"
        "$ErrorActionPreference = 'Stop'\n"
        f"$InstallerVersion = '{installer_version}'\n"
        "$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path\n"
        "$IndexFile = Join-Path $ScriptDir 'package-index.json'\n"
        "\n"
        "if (-not (Test-Path -LiteralPath $IndexFile)) {\n"
        "  throw 'package-index.json not found. Run this script from the deployment package root.'\n"
        "}\n"
        "$Manifest = [System.IO.File]::ReadAllText((Join-Path $ScriptDir 'manifest.json'), [System.Text.Encoding]::UTF8) | ConvertFrom-Json\n"
        "if (@($Manifest.deployModes) -notcontains $Mode) {\n"
        "  throw \"Deploy mode '$Mode' is not included in this package. Available modes: $(@($Manifest.deployModes) -join ', ')\"\n"
        "}\n"
        "\n"
        "function Require-Command([string]$Name) {\n"
        "  if (-not (Get-Command $Name -ErrorAction SilentlyContinue)) { throw \"Missing required command: $Name\" }\n"
        "}\n"
        "\n"
        "function Invoke-CheckedNativeCommand([string]$Description, [scriptblock]$Command) {\n"
        "  $output = & $Command\n"
        "  $exitCode = $LASTEXITCODE\n"
        "  if ($exitCode -ne 0) { throw \"$Description failed with exit code $exitCode.\" }\n"
        "  return $output\n"
        "}\n"
        "\n"
        "function Test-PackageDiskSpace {\n"
        "  $requiredBytes = 0\n"
        "  if ($Manifest.validationSummary -and $Manifest.validationSummary.packageIndexTotalBytes) {\n"
        "    $requiredBytes = [int64]$Manifest.validationSummary.packageIndexTotalBytes\n"
        "  }\n"
        "  if ($requiredBytes -le 0) { Write-Host 'Disk space check skipped: package size metadata unavailable.'; return }\n"
        "  $root = Get-Item -LiteralPath $ScriptDir\n"
        "  $drive = Get-PSDrive -Name $root.PSDrive.Name\n"
        "  $minimumBytes = $requiredBytes * 2\n"
        "  if ($drive.Free -lt $minimumBytes) {\n"
        "    throw \"Insufficient disk space: need at least $minimumBytes bytes, available $($drive.Free) bytes.\"\n"
        "  }\n"
        "  Write-Host \"Disk space check passed: available $($drive.Free) bytes.\"\n"
        "}\n"
        "\n"
        "function Test-ImageArchives {\n"
        "  $valuesPath = Join-Path $ScriptDir 'deploy-values.json'\n"
        "  if (-not (Test-Path -LiteralPath $valuesPath -PathType Leaf)) { Write-Host 'deploy-values.json not found; image archive preflight skipped.'; return }\n"
        "  $values = [System.IO.File]::ReadAllText($valuesPath, [System.Text.Encoding]::UTF8) | ConvertFrom-Json\n"
        "  if ($values.imageMode -ne 'image-archive') { return }\n"
        "  $missing = @()\n"
        "  foreach ($image in @($values.images)) {\n"
        "    if ($image.archiveFile) {\n"
        "      $archivePath = Join-Path (Join-Path $ScriptDir 'images/archives') $image.archiveFile\n"
        "      if (-not (Test-Path -LiteralPath $archivePath -PathType Leaf)) { $missing += $image.archiveFile }\n"
        "    }\n"
        "  }\n"
        "  if ($missing.Count) { throw \"Missing image archives: $($missing -join ', ')\" }\n"
        "  Write-Host 'Image archive preflight passed.'\n"
        "}\n"
        "\n"
        "function Invoke-LoadImageArchives {\n"
        "  $valuesPath = Join-Path $ScriptDir 'deploy-values.json'\n"
        "  if (-not (Test-Path -LiteralPath $valuesPath -PathType Leaf)) { return }\n"
        "  $values = [System.IO.File]::ReadAllText($valuesPath, [System.Text.Encoding]::UTF8) | ConvertFrom-Json\n"
        "  if ($values.imageMode -ne 'image-archive') { return }\n"
        "  $archiveDir = Join-Path $ScriptDir 'images/archives'\n"
        "  foreach ($image in @($values.images)) {\n"
        "    if (-not $image.archiveFile) { continue }\n"
        "    $archivePath = Join-Path $archiveDir $image.archiveFile\n"
        "    Write-Host \"Loading image archive: $($image.archiveFile)\"\n"
        "    Invoke-CheckedNativeCommand \"docker load $($image.archiveFile)\" { & docker load -i $archivePath | Out-Host }\n"
        "    if ($image.sourceRef -and $image.targetRef -and $image.sourceRef -ne $image.targetRef) { Invoke-CheckedNativeCommand \"docker tag $($image.sourceRef)\" { & docker tag $image.sourceRef $image.targetRef } | Out-Null }\n"
        "  }\n"
        "  Write-Host 'Image archives loaded.'\n"
        "}\n"
        "\n"
        "function Get-ComposeEnvFile([switch]$RequireConcreteEnv) {\n"
        "  $composeDir = Join-Path $ScriptDir 'docker-compose'\n"
        "  $envFile = Join-Path $composeDir '.env'\n"
        "  if (Test-Path -LiteralPath $envFile -PathType Leaf) { return $envFile }\n"
        "  $templateFile = Join-Path $composeDir '.env.template'\n"
        "  if ($RequireConcreteEnv) { throw 'docker-compose/.env not found. Copy docker-compose/.env.template to docker-compose/.env and replace all __REPLACE_WITH_ values before installation.' }\n"
        "  return $templateFile\n"
        "}\n"
        "\n"
        "function Test-SecretPlaceholders([string]$EnvFile) {\n"
        "  if (-not (Test-Path -LiteralPath $EnvFile -PathType Leaf)) { throw \"Secret file not found: $EnvFile\" }\n"
        "  $matches = Select-String -LiteralPath $EnvFile -Pattern '__REPLACE_WITH_' -SimpleMatch\n"
        "  if ($matches) {\n"
        "    $details = @($matches | ForEach-Object { \"$($_.Path):$($_.LineNumber):$($_.Line.Trim())\" }) -join [Environment]::NewLine\n"
        "    throw (\"Secret placeholders remain. Replace them before installation:\" + [Environment]::NewLine + $details)\n"
        "  }\n"
        "  Write-Host 'Secret placeholder check passed.'\n"
        "}\n"
        "\n"
        "function Test-DockerComposePrerequisites {\n"
        "  Require-Command 'docker'\n"
        "  Invoke-CheckedNativeCommand 'docker info' { & docker info | Out-Null }\n"
        "  Invoke-CheckedNativeCommand 'docker compose version' { & docker compose version | Out-Null }\n"
        "  Test-PackageDiskSpace\n"
        "  Test-ImageArchives\n"
        "  Write-Host 'Prerequisite check passed for docker-compose.'\n"
        "}\n"
        "\n"
        "function Invoke-DockerComposeDryRun {\n"
        "  Test-DockerComposePrerequisites\n"
        "  $envFile = Get-ComposeEnvFile -RequireConcreteEnv\n"
        "  Test-SecretPlaceholders $envFile\n"
        "  Invoke-CheckedNativeCommand 'docker compose config' { & docker compose --env-file $envFile -f (Join-Path $ScriptDir 'docker-compose/docker-compose.yml') config | Out-Null }\n"
        "  Write-Host 'Docker Compose config validation passed.'\n"
        "}\n"
        "\n"
        "function Invoke-DockerComposeInstall {\n"
        "  Test-DockerComposePrerequisites\n"
        "  $envFile = Get-ComposeEnvFile -RequireConcreteEnv\n"
        "  Test-SecretPlaceholders $envFile\n"
        "  Invoke-LoadImageArchives\n"
        "  Invoke-CheckedNativeCommand 'docker compose up' { & docker compose --env-file $envFile -f (Join-Path $ScriptDir 'docker-compose/docker-compose.yml') up -d }\n"
        "  $initScript = Join-Path $ScriptDir 'init/run-init.ps1'\n"
        "  if (Test-Path -LiteralPath $initScript -PathType Leaf) { & $initScript all }\n"
        "  else { Write-Host 'Init scripts are available under init/. Run them after services are configured.' }\n"
        "}\n"
        "\n"
        "function Convert-ComposePsJson([string[]]$Lines) {\n"
        "  $text = ($Lines -join [Environment]::NewLine).Trim()\n"
        "  if (-not $text) { return @() }\n"
        "  if ($text.StartsWith('[')) { return @($text | ConvertFrom-Json) }\n"
        "  return @($Lines | Where-Object { $_.Trim() } | ForEach-Object { $_ | ConvertFrom-Json })\n"
        "}\n"
        "\n"
        "function Invoke-DockerComposeHealthCheck {\n"
        "  Require-Command 'docker'\n"
        "  $envFile = Get-ComposeEnvFile -RequireConcreteEnv\n"
        "  $composeFile = Join-Path $ScriptDir 'docker-compose/docker-compose.yml'\n"
        "  $lines = Invoke-CheckedNativeCommand 'docker compose ps --format json' { & docker compose --env-file $envFile -f $composeFile ps --format json }\n"
        "  $bad = @()\n"
        "  foreach ($item in (Convert-ComposePsJson $lines)) {\n"
        "    $name = if ($item.Service) { $item.Service } elseif ($item.Name) { $item.Name } else { '<unknown>' }\n"
        "    $state = [string]$item.State\n"
        "    $health = [string]$item.Health\n"
        "    if ($state -and $state.ToLowerInvariant() -ne 'running') { $bad += \"${name}: state=$state\"; continue }\n"
        "    if ($health -and $health.ToLowerInvariant() -ne 'healthy') { $bad += \"${name}: health=$health\" }\n"
        "  }\n"
        "  if ($bad.Count) { throw \"Unhealthy docker-compose services: $($bad -join ', ')\" }\n"
        "  Write-Host 'Docker Compose service health check passed.'\n"
        "}\n"
        "\n"
        "function Invoke-Diagnostics([string]$DeployMode) {\n"
        "  $script = Join-Path $ScriptDir 'scripts/diagnostics.ps1'\n"
        "  if (Test-Path -LiteralPath $script -PathType Leaf) { & $script $DeployMode; return }\n"
        "  bash (Join-Path $ScriptDir 'scripts/diagnostics.sh') $DeployMode\n"
        "}\n"
        "\n"
        "function Get-DeploymentEnvValue([string]$Name) {\n"
        "  $envFile = Join-Path $ScriptDir 'docker-compose/.env'\n"
        "  if (-not (Test-Path -LiteralPath $envFile -PathType Leaf)) { return '' }\n"
        "  foreach ($line in [System.IO.File]::ReadLines($envFile, [System.Text.Encoding]::UTF8)) {\n"
        "    if ($line.StartsWith($Name + '=')) { return $line.Substring($Name.Length + 1) }\n"
        "  }\n"
        "  return ''\n"
        "}\n"
        "\n"
        "function Write-DeploymentAccessInfo([string]$DeployMode) {\n"
        "  if ($DeployMode -ne 'docker-compose') { return }\n"
        "  $threeAdminPassword = Get-DeploymentEnvValue 'DEFAULT_THREE_ADMIN_PASSWORD'\n"
        "  if (-not $threeAdminPassword) { $threeAdminPassword = Get-DeploymentEnvValue 'LOCAL_THREE_ADMIN_PASSWORD' }\n"
        "  if (-not $threeAdminPassword) { $threeAdminPassword = 'Admin@123456' }\n"
        "  Write-Host ''\n"
        "  Write-Host 'Deployment access information:'\n"
        "  Write-Host '  Frontend: http://127.0.0.1:18082/'\n"
        "  Write-Host '  Backend health: http://127.0.0.1:18081/health'\n"
        "  Write-Host '  Camunda: http://127.0.0.1:8080/'\n"
        "  Write-Host '  MinIO API: http://127.0.0.1:9000'\n"
        "  Write-Host '  Prometheus: http://127.0.0.1:9090'\n"
        "  Write-Host 'Three-admin initial accounts:'\n"
        "  Write-Host \"  system_admin / 系统管理员 / password: $threeAdminPassword\"\n"
        "  Write-Host \"  security_admin / 安全管理员 / password: $threeAdminPassword\"\n"
        "  Write-Host \"  audit_admin / 审计管理员 / password: $threeAdminPassword\"\n"
        "  Write-Host '  First login requires changing the password.'\n"
        "}\n"
        "\n"
        "if (-not $SkipVerify) { & (Join-Path $ScriptDir 'verify.ps1') }\n"
        "if (-not $Yes) {\n"
        "  Write-Host \"Installer $InstallerVersion will deploy mode: $Mode\"\n"
        "  $answer = Read-Host 'Continue? [y/N]'\n"
        "  if ($answer -ne 'y' -and $answer -ne 'Y') { Write-Host 'Installation canceled.'; exit 0 }\n"
        "}\n"
        "if ($Mode -eq 'k8s') {\n"
        "  if (-not $SkipDryRun) { bash (Join-Path $ScriptDir 'k8s/dry-run.sh') }\n"
        "  bash (Join-Path $ScriptDir 'k8s/install.sh')\n"
        "  if (-not $SkipHealthCheck) { bash (Join-Path $ScriptDir 'scripts/health-check.sh') k8s }\n"
        "} else {\n"
        "  if (-not $SkipDryRun) { Invoke-DockerComposeDryRun }\n"
        "  Invoke-DockerComposeInstall\n"
        "  if (-not $SkipHealthCheck) { Invoke-DockerComposeHealthCheck }\n"
        "}\n"
        "if (-not $SkipDiagnostics) { Invoke-Diagnostics $Mode }\n"
        "Write-Host \"Deployment succeeded for mode: $Mode.\"\n"
        "Write-DeploymentAccessInfo $Mode\n"
    )
