from __future__ import annotations

RUNTIME_ENV_ALIASES = {
    "DB_NAME": "DATABASE_NAME",
    "DB_DATABASE": "DATABASE_NAME",
    "POSTGRES_DB": "DATABASE_NAME",
    "POSTGRES_DATABASE": "DATABASE_NAME",
    "POSTGRESQL_DATABASE": "DATABASE_NAME",
    "DM_DATABASE": "DATABASE_NAME",
    "DB_URL": "DATABASE_URL",
    "DATASOURCE_URL": "DATABASE_URL",
    "SPRING_DATASOURCE_URL": "DATABASE_URL",
    "POSTGRES_URL": "DATABASE_URL",
    "POSTGRESQL_URL": "DATABASE_URL",
    "DB_USER": "DATABASE_USER",
    "DB_USERNAME": "DATABASE_USER",
    "DATASOURCE_USERNAME": "DATABASE_USER",
    "DATASOURCE_USER": "DATABASE_USER",
    "SPRING_DATASOURCE_USERNAME": "DATABASE_USER",
    "POSTGRES_USER": "DATABASE_USER",
    "POSTGRES_USERNAME": "DATABASE_USER",
    "POSTGRESQL_USER": "DATABASE_USER",
    "POSTGRESQL_USERNAME": "DATABASE_USER",
    "DM_USERNAME": "DATABASE_USER",
    "DB_PASSWORD": "DATABASE_PASSWORD",
    "DATASOURCE_PASSWORD": "DATABASE_PASSWORD",
    "SPRING_DATASOURCE_PASSWORD": "DATABASE_PASSWORD",
    "POSTGRES_PASSWORD": "DATABASE_PASSWORD",
    "POSTGRESQL_PASSWORD": "DATABASE_PASSWORD",
    "DM_PASSWORD": "DATABASE_PASSWORD",
    "SPRING_DATASOURCE_SCHEMA": "DATABASE_SCHEMA",
    "SPRING_DATASOURCE_HIKARI_SCHEMA": "DATABASE_SCHEMA",
    "SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_SCHEMA": "DATABASE_SCHEMA",
    "DB_SCHEMA": "DATABASE_SCHEMA",
    "POSTGRES_DSN": "POSTGRES_DSN",
    "POSTGRES_SCHEMA": "POSTGRES_SCHEMA",
    "POSTGRESQL_SCHEMA": "POSTGRES_SCHEMA",
    "MINIO_BUCKET": "MINIO_BUCKET",
    "MINIO_DEFAULT_BUCKET": "MINIO_BUCKET",
    "MINIO_BUCKET_NAME": "MINIO_BUCKET",
    "MINIO_BUCKETS": "MINIO_BUCKETS",
    "S3_BUCKET": "S3_BUCKET",
    "S3_BUCKET_NAME": "S3_BUCKET",
    "DOCUMENT_BUCKET": "DOCUMENT_BUCKET",
    "DOCUMENTS_BUCKET": "DOCUMENT_BUCKET",
    "FILE_BUCKET": "DOCUMENT_BUCKET",
    "OSS_BUCKET": "DOCUMENT_BUCKET",
    "QDRANT_COLLECTION": "QDRANT_COLLECTION",
    "QDRANT_COLLECTION_NAME": "QDRANT_COLLECTION",
    "QDRANT_COLLECTIONS": "QDRANT_COLLECTIONS",
    "VECTOR_COLLECTION": "VECTOR_COLLECTION",
    "VECTOR_COLLECTION_NAME": "VECTOR_COLLECTION",
    "REDIS_URL": "REDIS_URL",
    "REDIS_URI": "REDIS_URL",
    "SPRING_REDIS_URL": "REDIS_URL",
    "SPRING_DATA_REDIS_URL": "REDIS_URL",
    "REDIS_PASSWORD": "REDIS_PASSWORD",
    "REDIS_REQUIREPASS": "REDIS_PASSWORD",
    "REDIS_AUTH": "REDIS_PASSWORD",
    "SPRING_DATA_REDIS_PASSWORD": "REDIS_PASSWORD",
    "SPRING_REDIS_PASSWORD": "REDIS_PASSWORD",
    "MINIO_ROOT_USER": "MINIO_ROOT_USER",
    "MINIO_ACCESS_KEY": "MINIO_ROOT_USER",
    "MINIO_ROOT_PASSWORD": "MINIO_ROOT_PASSWORD",
    "MINIO_SECRET_KEY": "MINIO_ROOT_PASSWORD",
    "QDRANT_API_KEY": "QDRANT_API_KEY",
    "QDRANT_SERVICE_API_KEY": "QDRANT_API_KEY",
    "QDRANT__SERVICE__API_KEY": "QDRANT_API_KEY",
    "VECTOR_API_KEY": "QDRANT_API_KEY",
    "IOTDB_URL": "IOTDB_URL",
    "IOTDB_URI": "IOTDB_URL",
    "IOTDB_USER": "IOTDB_USER",
    "IOTDB_USERNAME": "IOTDB_USER",
    "IOTDB_PASSWORD": "IOTDB_PASSWORD",
    "EAM_IOTDB_PASSWORD": "IOTDB_PASSWORD",
    "CAMUNDA_ADMIN_USER": "CAMUNDA_ADMIN_USER",
    "CAMUNDA_ADMIN_PASSWORD": "CAMUNDA_ADMIN_PASSWORD",
}

CANONICAL_RUNTIME_ENV_NAMES = {
    "DATABASE_NAME",
    "DATABASE_URL",
    "DATABASE_USER",
    "DATABASE_PASSWORD",
    "DATABASE_SCHEMA",
    "REDIS_PASSWORD",
    "MINIO_ROOT_USER",
    "MINIO_ROOT_PASSWORD",
    "QDRANT_API_KEY",
    "IOTDB_USER",
    "IOTDB_PASSWORD",
    "CAMUNDA_ADMIN_USER",
    "CAMUNDA_ADMIN_PASSWORD",
}


def runtime_env_alias(normalized: str) -> str:
    if normalized in RUNTIME_ENV_ALIASES:
        return RUNTIME_ENV_ALIASES[normalized]
    return normalized if normalized in CANONICAL_RUNTIME_ENV_NAMES else ""


def runtime_env_alias_for_source(source_name: str, key: str) -> str:
    normalized_key = _normalize(key)
    direct = runtime_env_alias(normalized_key)
    if direct:
        return direct
    source = _normalize(source_name)
    if normalized_key not in {"PASSWORD", "ROOT_PASSWORD", "ADMIN_PASSWORD", "API_KEY"}:
        return ""
    if "REDIS" in source:
        return "REDIS_PASSWORD"
    if "MINIO" in source:
        return "MINIO_ROOT_PASSWORD"
    if "QDRANT" in source or "VECTOR" in source:
        return "QDRANT_API_KEY"
    if "IOTDB" in source:
        return "IOTDB_PASSWORD"
    if "CAMUNDA" in source:
        return "CAMUNDA_ADMIN_PASSWORD"
    if "POSTGRES" in source or "POSTGRESQL" in source or "DATABASE" in source:
        return "DATABASE_PASSWORD"
    return ""


def _normalize(value: str) -> str:
    return "".join(ch if ch.isalnum() else "_" for ch in value).strip("_").upper()
