from __future__ import annotations

from dataclasses import dataclass
from pathlib import PurePosixPath


VERIFIER_VERSION = "1.0.0"


@dataclass(frozen=True)
class RenderedVerifyFile:
    path: PurePosixPath
    content: str
    executable: bool = False


def render_package_verify_files() -> list[RenderedVerifyFile]:
    return [
        RenderedVerifyFile(PurePosixPath("verify.sh"), _verify_sh(), executable=True),
        RenderedVerifyFile(PurePosixPath("verify.ps1"), _verify_ps1()),
    ]


def _verify_sh() -> str:
    return (
        "#!/usr/bin/env bash\n"
        "set -euo pipefail\n"
        f'VERIFIER_VERSION="{VERIFIER_VERSION}"\n'
        'SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"\n'
        "\n"
        "fail() {\n"
        '  echo "Package verification failed: $1" >&2\n'
        "  exit 1\n"
        "}\n"
        "\n"
        "require_file() {\n"
        '  if [ ! -f "${SCRIPT_DIR}/$1" ]; then\n'
        '    fail "missing required file: $1"\n'
        "  fi\n"
        "}\n"
        "\n"
        'echo "Deployment package verifier ${VERIFIER_VERSION}"\n'
        "require_file manifest.json\n"
        "require_file package-index.json\n"
        "require_file security/SHA256SUMS\n"
        "require_file security/image-digest-lock.json\n"
        "require_file images/images.txt\n"
        "\n"
        'SHA_CHECK_FILE="$(mktemp)"\n'
        'trap \'rm -f "${SHA_CHECK_FILE}"\' EXIT\n'
        'awk \'$2 != "docker-compose/.env" && $2 != "docs/quality-report.runtime.md"\' "${SCRIPT_DIR}/security/SHA256SUMS" > "${SHA_CHECK_FILE}"\n'
        "\n"
        "if command -v sha256sum >/dev/null 2>&1; then\n"
        '  (cd "${SCRIPT_DIR}" && sha256sum -c "${SHA_CHECK_FILE}")\n'
        "elif command -v shasum >/dev/null 2>&1; then\n"
        '  (cd "${SCRIPT_DIR}" && shasum -a 256 -c "${SHA_CHECK_FILE}")\n'
        "else\n"
        '  fail "sha256sum or shasum is required"\n'
        "fi\n"
        "\n"
        "PYTHON_BIN=\"\"\n"
        "if command -v python3 >/dev/null 2>&1; then\n"
        "  PYTHON_BIN=python3\n"
        "elif command -v python >/dev/null 2>&1; then\n"
        "  PYTHON_BIN=python\n"
        "fi\n"
        "\n"
        'if [ -n "${PYTHON_BIN}" ]; then\n'
        '  "${PYTHON_BIN}" - "${SCRIPT_DIR}" <<\'PY\'\n'
        "import hashlib\n"
        "import json\n"
        "import sys\n"
        "from pathlib import Path\n"
        "\n"
        "root = Path(sys.argv[1])\n"
        "\n"
        "def fail(message: str) -> None:\n"
        "    raise SystemExit(f\"Package index verification failed: {message}\")\n"
        "\n"
        "def digest(path: Path) -> str:\n"
        "    value = hashlib.sha256()\n"
        "    with path.open(\"rb\") as handle:\n"
        "        for chunk in iter(lambda: handle.read(1024 * 1024), b\"\"):\n"
        "            value.update(chunk)\n"
        "    return value.hexdigest()\n"
        "\n"
        "runtime_files = {\"docker-compose/.env\", \"docs/quality-report.runtime.md\"}\n"
        "\n"
        "index = json.loads((root / \"package-index.json\").read_text(encoding=\"utf-8\"))\n"
        "if index.get(\"schemaVersion\") != \"deployment-package-index/v1\":\n"
        "    fail(\"unsupported package-index schema\")\n"
        "\n"
        "required = {\n"
        "    \"manifest.json\",\n"
        "    \"README.md\",\n"
        "    \"install.sh\",\n"
        "    \"install.ps1\",\n"
        "    \"verify.sh\",\n"
        "    \"verify.ps1\",\n"
        "    \"quality-gate.sh\",\n"
        "    \"quality-gate.ps1\",\n"
        "    \"docs/quality-report.md\",\n"
        "    \"images/images.txt\",\n"
        "    \"security/image-digest-lock.json\",\n"
        "    \"security/SHA256SUMS\",\n"
        "}\n"
        "for rel in required:\n"
        "    if not (root / rel).is_file():\n"
        "        fail(f\"missing required file: {rel}\")\n"
        "\n"
        "sha_paths = set()\n"
        "for line in (root / \"security\" / \"SHA256SUMS\").read_text(encoding=\"utf-8\").splitlines():\n"
        "    if not line.strip():\n"
        "        continue\n"
        "    parts = line.split(None, 1)\n"
        "    if len(parts) != 2:\n"
        "        fail(f\"invalid SHA256SUMS line: {line}\")\n"
        "    rel = parts[1].strip()\n"
        "    if rel not in runtime_files:\n"
        "        sha_paths.add(rel)\n"
        "actual_files = {path.relative_to(root).as_posix() for path in root.rglob(\"*\") if path.is_file()}\n"
        "expected_signed = actual_files - {\"security/SHA256SUMS\"} - runtime_files\n"
        "if sha_paths != expected_signed:\n"
        "    unsigned = sorted(expected_signed - sha_paths)\n"
        "    stale = sorted(sha_paths - expected_signed)\n"
        "    fail(f\"SHA256SUMS file set mismatch; unsigned={unsigned}; stale={stale}\")\n"
        "\n"
        "indexed_paths = set()\n"
        "for section, entries in index.get(\"sections\", {}).items():\n"
        "    if not isinstance(entries, list):\n"
        "        fail(f\"section {section} is not a list\")\n"
        "    for entry in entries:\n"
        "        rel = entry.get(\"path\")\n"
        "        if not rel:\n"
        "            fail(f\"section {section} has an entry without path\")\n"
        "        if rel in runtime_files:\n"
        "            continue\n"
        "        if rel in indexed_paths:\n"
        "            fail(f\"file is indexed more than once: {rel}\")\n"
        "        indexed_paths.add(rel)\n"
        "        path = root / rel\n"
        "        if not path.is_file():\n"
        "            fail(f\"indexed file is missing: {rel}\")\n"
        "        if path.stat().st_size != entry.get(\"size\"):\n"
        "            fail(f\"indexed file size changed: {rel}\")\n"
        "        if digest(path) != entry.get(\"sha256\"):\n"
        "            fail(f\"indexed file checksum changed: {rel}\")\n"
        "expected_indexed = actual_files - {\"package-index.json\", \"security/SHA256SUMS\"} - runtime_files\n"
        "if indexed_paths != expected_indexed:\n"
        "    unindexed = sorted(expected_indexed - indexed_paths)\n"
        "    stale = sorted(indexed_paths - expected_indexed)\n"
        "    fail(f\"package-index file set mismatch; unindexed={unindexed}; stale={stale}\")\n"
        "\n"
        "lock = json.loads((root / \"security\" / \"image-digest-lock.json\").read_text(encoding=\"utf-8\"))\n"
        "archives = {item.get(\"file\"): item for item in lock.get(\"archives\", [])}\n"
        "manifest = json.loads((root / \"manifest.json\").read_text(encoding=\"utf-8\"))\n"
        "if manifest.get(\"imageMode\") == \"image-archive\":\n"
        "    for image in manifest.get(\"imageEntries\", []):\n"
        "        archive_file = image.get(\"archiveFile\")\n"
        "        if archive_file not in archives:\n"
        "            fail(f\"image archive is not locked: {archive_file}\")\n"
        "\n"
        "for name, entry in archives.items():\n"
        "    if not name:\n"
        "        fail(\"image archive lock entry has no file name\")\n"
        "    path = root / \"images\" / \"archives\" / name\n"
        "    if not path.is_file():\n"
        "        fail(f\"locked image archive is missing: {name}\")\n"
        "    if path.stat().st_size != entry.get(\"size\"):\n"
        "        fail(f\"locked image archive size changed: {name}\")\n"
        "    if digest(path) != entry.get(\"sha256\"):\n"
        "        fail(f\"locked image archive checksum changed: {name}\")\n"
        "\n"
        "print(\"Package index verification passed.\")\n"
        "PY\n"
        "else\n"
        '  echo "Python is not available; skipped package-index structural checks."\n'
        "fi\n"
        "\n"
        'echo "Deployment package verification passed."\n'
    )


def _verify_ps1() -> str:
    return (
        "$ErrorActionPreference = 'Stop'\n"
        f"$VerifierVersion = '{VERIFIER_VERSION}'\n"
        "$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path\n"
        "\n"
        "function Fail([string]$Message) {\n"
        "  throw \"Package verification failed: $Message\"\n"
        "}\n"
        "\n"
        "function Require-File([string]$RelativePath) {\n"
        "  $path = Join-Path $ScriptDir $RelativePath\n"
        "  if (-not (Test-Path -LiteralPath $path -PathType Leaf)) {\n"
        "    Fail \"missing required file: $RelativePath\"\n"
        "  }\n"
        "}\n"
        "\n"
        "function Get-RelativeFileHash([string]$RelativePath) {\n"
        "  $path = Join-Path $ScriptDir $RelativePath\n"
        "  if (Get-Command Get-FileHash -ErrorAction SilentlyContinue) {\n"
        "    return (Get-FileHash -Algorithm SHA256 -LiteralPath $path).Hash.ToLowerInvariant()\n"
        "  }\n"
        "  $stream = [System.IO.File]::OpenRead($path)\n"
        "  try {\n"
        "    $sha = [System.Security.Cryptography.SHA256]::Create()\n"
        "    $bytes = $sha.ComputeHash($stream)\n"
        "    return ([System.BitConverter]::ToString($bytes) -replace '-', '').ToLowerInvariant()\n"
        "  } finally {\n"
        "    $stream.Dispose()\n"
        "  }\n"
        "}\n"
        "\n"
        "function Read-Utf8Text([string]$Path) {\n"
        "  return [System.IO.File]::ReadAllText($Path, [System.Text.Encoding]::UTF8)\n"
        "}\n"
        "\n"
        "function Read-Utf8Lines([string]$Path) {\n"
        "  return [System.IO.File]::ReadAllLines($Path, [System.Text.Encoding]::UTF8)\n"
        "}\n"
        "\n"
        "$RuntimeFiles = @{\n"
        "  'docker-compose/.env' = $true\n"
        "  'docs/quality-report.runtime.md' = $true\n"
        "}\n"
        "\n"
        "Write-Host \"Deployment package verifier $VerifierVersion\"\n"
        "Require-File 'manifest.json'\n"
        "Require-File 'package-index.json'\n"
        "Require-File 'security/SHA256SUMS'\n"
        "Require-File 'security/image-digest-lock.json'\n"
        "Require-File 'images/images.txt'\n"
        "\n"
        "$shaFile = Join-Path $ScriptDir 'security/SHA256SUMS'\n"
        "foreach ($line in Read-Utf8Lines $shaFile) {\n"
        "  if ([string]::IsNullOrWhiteSpace($line)) { continue }\n"
        "  $parts = $line -split '\\s+', 2\n"
        "  if ($parts.Count -ne 2) { Fail \"invalid SHA256SUMS line: $line\" }\n"
        "  $expected = $parts[0].ToLowerInvariant()\n"
        "  $relativePath = $parts[1].Trim()\n"
        "  if ($RuntimeFiles.ContainsKey($relativePath)) { continue }\n"
        "  Require-File $relativePath\n"
        "  $actual = Get-RelativeFileHash $relativePath\n"
        "  if ($actual -ne $expected) { Fail \"checksum changed: $relativePath\" }\n"
        "}\n"
        "\n"
        "$index = Read-Utf8Text (Join-Path $ScriptDir 'package-index.json') | ConvertFrom-Json\n"
        "if ($index.schemaVersion -ne 'deployment-package-index/v1') {\n"
        "  Fail 'unsupported package-index schema'\n"
        "}\n"
        "\n"
        "$required = @(\n"
        "  'manifest.json',\n"
        "  'README.md',\n"
        "  'install.sh',\n"
        "  'install.ps1',\n"
        "  'verify.sh',\n"
        "  'verify.ps1',\n"
        "  'quality-gate.sh',\n"
        "  'quality-gate.ps1',\n"
        "  'docs/quality-report.md',\n"
        "  'images/images.txt',\n"
        "  'security/image-digest-lock.json',\n"
        "  'security/SHA256SUMS'\n"
        ")\n"
        "foreach ($item in $required) { Require-File $item }\n"
        "\n"
        "$actualFiles = @{}\n"
        "Push-Location $ScriptDir\n"
        "try {\n"
        "  Get-ChildItem -Recurse -File | ForEach-Object {\n"
        "    $relative = (Resolve-Path -LiteralPath $_.FullName -Relative).TrimStart('.').TrimStart('\\').TrimStart('/').Replace('\\', '/')\n"
        "    $actualFiles[$relative] = $true\n"
        "  }\n"
        "} finally {\n"
        "  Pop-Location\n"
        "}\n"
        "$shaPaths = @{}\n"
        "foreach ($line in Read-Utf8Lines $shaFile) {\n"
        "  if ([string]::IsNullOrWhiteSpace($line)) { continue }\n"
        "  $parts = $line -split '\\s+', 2\n"
        "  if ($parts.Count -ne 2) { Fail \"invalid SHA256SUMS line: $line\" }\n"
        "  $relativePath = $parts[1].Trim()\n"
        "  if (-not $RuntimeFiles.ContainsKey($relativePath)) { $shaPaths[$relativePath] = $true }\n"
        "}\n"
        "$expectedSigned = @{}\n"
        "foreach ($path in $actualFiles.Keys) {\n"
        "  if ($path -ne 'security/SHA256SUMS' -and -not $RuntimeFiles.ContainsKey($path)) { $expectedSigned[$path] = $true }\n"
        "}\n"
        "$unsigned = @($expectedSigned.Keys | Where-Object { -not $shaPaths.ContainsKey($_) } | Sort-Object)\n"
        "$staleSigned = @($shaPaths.Keys | Where-Object { -not $expectedSigned.ContainsKey($_) } | Sort-Object)\n"
        "if ($unsigned.Count -or $staleSigned.Count) {\n"
        "  Fail \"SHA256SUMS file set mismatch; unsigned=$($unsigned -join ','); stale=$($staleSigned -join ',')\"\n"
        "}\n"
        "\n"
        "$indexedPaths = @{}\n"
        "foreach ($section in $index.sections.PSObject.Properties) {\n"
        "  foreach ($entry in @($section.Value)) {\n"
        "    if (-not $entry.path) { Fail \"section $($section.Name) has an entry without path\" }\n"
        "    if ($RuntimeFiles.ContainsKey($entry.path)) { continue }\n"
        "    if ($indexedPaths.ContainsKey($entry.path)) { Fail \"file is indexed more than once: $($entry.path)\" }\n"
        "    $indexedPaths[$entry.path] = $true\n"
        "    $path = Join-Path $ScriptDir $entry.path\n"
        "    Require-File $entry.path\n"
        "    $file = Get-Item -LiteralPath $path\n"
        "    if ($file.Length -ne $entry.size) { Fail \"indexed file size changed: $($entry.path)\" }\n"
        "    if ((Get-RelativeFileHash $entry.path) -ne $entry.sha256) { Fail \"indexed file checksum changed: $($entry.path)\" }\n"
        "  }\n"
        "}\n"
        "$expectedIndexed = @{}\n"
        "foreach ($path in $actualFiles.Keys) {\n"
        "  if ($path -ne 'package-index.json' -and $path -ne 'security/SHA256SUMS' -and -not $RuntimeFiles.ContainsKey($path)) { $expectedIndexed[$path] = $true }\n"
        "}\n"
        "$unindexed = @($expectedIndexed.Keys | Where-Object { -not $indexedPaths.ContainsKey($_) } | Sort-Object)\n"
        "$staleIndexed = @($indexedPaths.Keys | Where-Object { -not $expectedIndexed.ContainsKey($_) } | Sort-Object)\n"
        "if ($unindexed.Count -or $staleIndexed.Count) {\n"
        "  Fail \"package-index file set mismatch; unindexed=$($unindexed -join ','); stale=$($staleIndexed -join ',')\"\n"
        "}\n"
        "\n"
        "$manifest = Read-Utf8Text (Join-Path $ScriptDir 'manifest.json') | ConvertFrom-Json\n"
        "$lock = Read-Utf8Text (Join-Path $ScriptDir 'security/image-digest-lock.json') | ConvertFrom-Json\n"
        "$archiveByName = @{}\n"
        "foreach ($archive in @($lock.archives)) { $archiveByName[$archive.file] = $archive }\n"
        "if ($manifest.imageMode -eq 'image-archive') {\n"
        "  foreach ($image in @($manifest.imageEntries)) {\n"
        "    if (-not $archiveByName.ContainsKey($image.archiveFile)) { Fail \"image archive is not locked: $($image.archiveFile)\" }\n"
        "  }\n"
        "}\n"
        "foreach ($archive in @($lock.archives)) {\n"
        "  $relativePath = Join-Path 'images/archives' $archive.file\n"
        "  Require-File $relativePath\n"
        "  $path = Join-Path $ScriptDir $relativePath\n"
        "  $file = Get-Item -LiteralPath $path\n"
        "  if ($file.Length -ne $archive.size) { Fail \"locked image archive size changed: $($archive.file)\" }\n"
        "  if ((Get-RelativeFileHash $relativePath) -ne $archive.sha256) { Fail \"locked image archive checksum changed: $($archive.file)\" }\n"
        "}\n"
        "\n"
        "Write-Host 'Deployment package verification passed.'\n"
    )
