-- MES Lite DM Schema Initialization
-- This script uses DM-specific syntax and is idempotent.
-- Production: execute by DBA with appropriate tablespace configuration.

-- Create MES basic tables
CREATE TABLE MES_PRODUCTION_ORDERS (
  ID VARCHAR2(36) PRIMARY KEY,
  ORDER_NO VARCHAR2(50) UNIQUE NOT NULL,
  PRODUCT_CODE VARCHAR2(50) NOT NULL,
  PRODUCT_NAME VARCHAR2(255) NOT NULL,
  QUANTITY NUMBER(10,2) NOT NULL,
  STATUS VARCHAR2(50) DEFAULT 'PENDING',
  PLAN_START_DATE TIMESTAMP,
  PLAN_END_DATE TIMESTAMP,
  ACTUAL_START_DATE TIMESTAMP,
  ACTUAL_END_DATE TIMESTAMP,
  CREATED_AT TIMESTAMP DEFAULT SYSDATE,
  UPDATED_AT TIMESTAMP DEFAULT SYSDATE
);

CREATE TABLE MES_WORK_STATIONS (
  ID VARCHAR2(36) PRIMARY KEY,
  STATION_CODE VARCHAR2(50) UNIQUE NOT NULL,
  STATION_NAME VARCHAR2(255) NOT NULL,
  WORKSHOP VARCHAR2(100),
  STATUS VARCHAR2(50) DEFAULT 'IDLE',
  CAPACITY NUMBER(10,2),
  CREATED_AT TIMESTAMP DEFAULT SYSDATE,
  UPDATED_AT TIMESTAMP DEFAULT SYSDATE
);

CREATE TABLE MES_QUALITY_CHECKS (
  ID VARCHAR2(36) PRIMARY KEY,
  ORDER_ID VARCHAR2(36) NOT NULL,
  CHECK_TYPE VARCHAR2(50) NOT NULL,
  CHECK_RESULT VARCHAR2(50),
  INSPECTOR VARCHAR2(100),
  CHECK_TIME TIMESTAMP DEFAULT SYSDATE,
  REMARKS CLOB,
  CREATED_AT TIMESTAMP DEFAULT SYSDATE
);

CREATE INDEX IDX_PROD_ORDERS_NO ON MES_PRODUCTION_ORDERS(ORDER_NO);
CREATE INDEX IDX_PROD_ORDERS_STATUS ON MES_PRODUCTION_ORDERS(STATUS);
CREATE INDEX IDX_WORK_STATIONS_CODE ON MES_WORK_STATIONS(STATION_CODE);
CREATE INDEX IDX_QUALITY_CHECKS_ORDER ON MES_QUALITY_CHECKS(ORDER_ID);

-- Insert default MES data
INSERT INTO MES_WORK_STATIONS (ID, STATION_CODE, STATION_NAME, WORKSHOP, STATUS)
SELECT SYS_GUID(), 'WS001', '装配工位1', '装配车间', 'IDLE' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM MES_WORK_STATIONS WHERE STATION_CODE = 'WS001');

INSERT INTO MES_WORK_STATIONS (ID, STATION_CODE, STATION_NAME, WORKSHOP, STATUS)
SELECT SYS_GUID(), 'WS002', '检测工位1', '质检车间', 'IDLE' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM MES_WORK_STATIONS WHERE STATION_CODE = 'WS002');

COMMIT;

